/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import common.dto.Result;
import java.util.ArrayList;
import java.util.Arrays;
import common.enums.Rol;
import javax.swing.JOptionPane;
import client.controller.UserController;

/**
 *
 * @author Fabian
 */
public class JDMantenimientoUsuario extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDMantenimientoUsuario.class.getName());
    private final UserController userController;
    private int idUsuario = 0;

    /**
     * Creates new form JDAgregarUsuario
     */
    public JDMantenimientoUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCombox();
        this.userController = ClientBootstrap.buildUserController();
        modoAgregar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRegistrar = new javax.swing.JButton();
        TfEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TfConfirmarPassword = new javax.swing.JPasswordField();
        TfPassword = new javax.swing.JPasswordField();
        TfName = new javax.swing.JTextField();
        JFtelefono = new javax.swing.JFormattedTextField();
        TfPhoneNumeber = new javax.swing.JTextField();
        CbxRoles = new javax.swing.JComboBox<>();
        BtnActualizar = new javax.swing.JButton();
        BtnElimina = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Usuario");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRegistrar.setBackground(new java.awt.Color(51, 102, 255));
        BtnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setText("Agregar");
        BtnRegistrar.setBorder(null);
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 250, 50));

        TfEmail.setBackground(new java.awt.Color(255, 255, 255));
        TfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfEmail.setText("  Email");
        TfEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        TfEmail.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(TfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 250, 40));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("USER ADD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        TfConfirmarPassword.setBackground(new java.awt.Color(255, 255, 255));
        TfConfirmarPassword.setText("jPasswordField1");
        TfConfirmarPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        getContentPane().add(TfConfirmarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 250, 40));

        TfPassword.setBackground(new java.awt.Color(255, 255, 255));
        TfPassword.setText("jPasswordField1");
        TfPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        getContentPane().add(TfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 250, 40));

        TfName.setBackground(new java.awt.Color(255, 255, 255));
        TfName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfName.setText("  Name");
        TfName.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        TfName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(TfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 250, 40));

        JFtelefono.setBackground(new java.awt.Color(255, 255, 255));
        JFtelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        try {
            JFtelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFtelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(JFtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 250, 40));

        TfPhoneNumeber.setBackground(new java.awt.Color(255, 255, 255));
        TfPhoneNumeber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfPhoneNumeber.setText("  Phone Number");
        TfPhoneNumeber.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        TfPhoneNumeber.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TfPhoneNumeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPhoneNumeberActionPerformed(evt);
            }
        });
        getContentPane().add(TfPhoneNumeber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 250, 40));

        CbxRoles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CbxRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbxRoles.setToolTipText("Rol");
        CbxRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxRolesActionPerformed(evt);
            }
        });
        getContentPane().add(CbxRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 250, 40));

        BtnActualizar.setBackground(new java.awt.Color(51, 102, 255));
        BtnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        BtnActualizar.setText("Actualiza");
        BtnActualizar.setBorder(null);
        BtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizarMouseClicked(evt);
            }
        });
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 250, 50));

        BtnElimina.setBackground(new java.awt.Color(255, 51, 51));
        BtnElimina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnElimina.setForeground(new java.awt.Color(255, 255, 255));
        BtnElimina.setText("Elimina");
        BtnElimina.setBorder(null);
        BtnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnElimina, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 250, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Personal data");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText(" Access data");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/image2_360x680_high_dpi.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        obtenerDatos();
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void TfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEmailActionPerformed

    private void TfPhoneNumeberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPhoneNumeberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPhoneNumeberActionPerformed

    private void JFtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFtelefonoActionPerformed

    private void CbxRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxRolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxRolesActionPerformed

    private void BtnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminaActionPerformed
        eliminarUsuario();
    }//GEN-LAST:event_BtnEliminaActionPerformed

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void BtnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizarMouseClicked
        actualizarDatos();
    }//GEN-LAST:event_BtnActualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDMantenimientoUsuario dialog = new JDMantenimientoUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnElimina;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JComboBox<String> CbxRoles;
    private javax.swing.JFormattedTextField JFtelefono;
    private javax.swing.JPasswordField TfConfirmarPassword;
    private javax.swing.JTextField TfEmail;
    private javax.swing.JTextField TfName;
    private javax.swing.JPasswordField TfPassword;
    private javax.swing.JTextField TfPhoneNumeber;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    private void cargarCombox() {
        ArrayList<Rol> lista = obtenerRoles();
        CbxRoles.removeAllItems();
        for (Rol rol : lista) {
            CbxRoles.addItem(rol.toString());
        }
    }

    private ArrayList<Rol> obtenerRoles() {
        return new ArrayList<>(Arrays.asList(Rol.values()));
    }

    public void modoAgregar() {
        idUsuario = 0;

        TfName.setText("");
        TfEmail.setText("");
        TfPassword.setText("");
        TfConfirmarPassword.setText("");
        JFtelefono.setText("");

        if (CbxRoles.getItemCount() > 0) {
            CbxRoles.setSelectedIndex(0);
        }

        BtnRegistrar.setVisible(true);
        BtnElimina.setVisible(false);
        BtnActualizar.setVisible(false);
        setTitle("Agregar Usuario");
        jLabel4.setText("USER ADD");
    }

    public void cargarDatosUsuario(int idUsuario, String nombre, String email, String rol) {
        this.idUsuario = idUsuario;

        TfName.setText(nombre);
        TfEmail.setText(email);

        CbxRoles.setSelectedItem(rol);

        TfPassword.setText("");
        TfConfirmarPassword.setText("");
        JFtelefono.setText("");

        BtnElimina.setVisible(true);
        BtnActualizar.setVisible(true);
        BtnRegistrar.setVisible(false);
        setTitle("Actualizar Usuario");
        jLabel4.setText("USER UPDATE");
    }

    private void obtenerDatos() {
        String username = TfEmail.getText().toString();
        String password = TfPassword.getText().toString();
        String confirmPassword = TfConfirmarPassword.getText().toString();
        String telefono = JFtelefono.getText().toString();
        String nombre = TfName.getText().toString();
        String rolSeleccionado = CbxRoles.getSelectedItem().toString();
        Rol rol = Rol.valueOf(rolSeleccionado);

        try {

            Result<Void> result = userController.createUser(
                    username,
                    password,
                    confirmPassword,
                    telefono,
                    nombre,
                    rol
            );

            if (result.ok) {
                JOptionPane.showMessageDialog(
                        rootPane,
                        result.message,
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE
                );
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(
                        rootPane,
                        result.message,
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void actualizarDatos() {
        String username = TfEmail.getText().trim();
        String password = new String(TfPassword.getPassword()).trim();
        String confirmPassword = new String(TfConfirmarPassword.getPassword()).trim();
        String telefono = JFtelefono.getText().trim();
        String nombre = TfName.getText().trim();

        String rolSeleccionado = CbxRoles.getSelectedItem().toString();
        Rol rol = Rol.valueOf(rolSeleccionado);

        try {
            Result<Void> result = userController.updateUser(
                    idUsuario,
                    username,
                    password,
                    confirmPassword,
                    telefono,
                    nombre,
                    rol
            );

            if (result.ok) {
                JOptionPane.showMessageDialog(
                        rootPane,
                        result.message,
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE
                );

                this.dispose();

                if (JIFGestionUsers.instancia != null) {
                    JIFGestionUsers.instancia.cargarUsuarios();
                }

            } else {
                JOptionPane.showMessageDialog(
                        rootPane,
                        result.message,
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void eliminarUsuario() {
        if (idUsuario <= 0) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Debe seleccionar un usuario válido",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
                rootPane,
                "¿Seguro que desea eliminar este usuario?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        Result<Void> result = userController.deleteUser(idUsuario);

        if (result.ok) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    result.message,
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
            );

            this.dispose();

            if (JIFGestionUsers.instancia != null) {
                JIFGestionUsers.instancia.cargarUsuarios();
            }

        } else {
            JOptionPane.showMessageDialog(
                    rootPane,
                    result.message,
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

}
