/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import client.controller.PeticionController;
import common.dto.Result;
import common.enums.EstadoPeticion;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class JDMantenimientoPeticion extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDMantenimientoPeticion.class.getName());
    private final PeticionController peticionController;
    private int idPeticion = 0;

    /**
     * Creates new form JDMantenimientoPeticion
     */
    public JDMantenimientoPeticion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.peticionController = ClientBootstrap.buildPeticionController();
        cargarComboEstados();
        TfId.setEditable(false);
        TfUsuario.setEditable(false);
        TfFecha.setEditable(false);

        TfId.setFocusable(false);
        TfUsuario.setFocusable(false);
        TfFecha.setFocusable(false);

        CbxTipoSolicitud.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRegistrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TfFecha = new javax.swing.JFormattedTextField();
        TfUsuario = new javax.swing.JTextField();
        TfId = new javax.swing.JTextField();
        CbxTipoSolicitud = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRegistrar.setBackground(new java.awt.Color(51, 102, 255));
        BtnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setText("Enviar");
        BtnRegistrar.setBorder(null);
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 250, 50));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("PETICION");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        TfFecha.setBackground(new java.awt.Color(255, 255, 255));
        TfFecha.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        TfFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        TfFecha.setText("Fecha");
        getContentPane().add(TfFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 250, 40));

        TfUsuario.setBackground(new java.awt.Color(255, 255, 255));
        TfUsuario.setText("Usario");
        TfUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        TfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(TfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 250, 40));

        TfId.setBackground(new java.awt.Color(255, 255, 255));
        TfId.setText("ID");
        TfId.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        TfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfIdActionPerformed(evt);
            }
        });
        getContentPane().add(TfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 250, 40));

        CbxTipoSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CbxTipoSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 250, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText(" Access data");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/image2_360x680_high_dpi.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        actualizarPeticion();
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void TfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfUsuarioActionPerformed

    private void TfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDMantenimientoPeticion dialog = new JDMantenimientoPeticion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void cargarComboEstados() {
        CbxTipoSolicitud.removeAllItems();

        for (EstadoPeticion estado : EstadoPeticion.values()) {
            CbxTipoSolicitud.addItem(estado.name());
        }
    }

    public void cargarDatosPeticion(int idPeticion, String usuario, String fecha, String estado) {
        this.idPeticion = idPeticion;

        TfId.setText(String.valueOf(idPeticion));
        TfUsuario.setText(usuario);
        TfFecha.setText(fecha);

        CbxTipoSolicitud.setSelectedItem(estado);

        TfId.setEditable(false);
        TfUsuario.setEditable(false);
        TfFecha.setEditable(false);
    }

    private void actualizarPeticion() {
        try {
            EstadoPeticion estado = EstadoPeticion.valueOf(
                    CbxTipoSolicitud.getSelectedItem().toString()
            );

            Result<Void> result = peticionController.updateEstadoPeticion(
                    idPeticion,
                    estado
            );

            if (result.ok) {
                JOptionPane.showMessageDialog(
                        rootPane,
                        result.message,
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE
                );

                this.dispose();

                if (JIFAtender.instancia != null) {
                    JIFAtender.instancia.cargarPeticiones();
                }

            } else {
                JOptionPane.showMessageDialog(
                        rootPane,
                        result.message,
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JComboBox<String> CbxTipoSolicitud;
    private javax.swing.JFormattedTextField TfFecha;
    private javax.swing.JTextField TfId;
    private javax.swing.JTextField TfUsuario;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
