/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import common.dto.Result;
import common.enums.EstadoTurno;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import server.model.Turno;
import client.controller.TurnoController;

/**
 *
 * @author Fabian
 */
public class JDMantenimientoTurno extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDMantenimientoTurno.class.getName());
    private final TurnoController turnoController;
    private int idTurno = 0;

    /**
     * Creates new form JDAgregarTurno
     */
    public JDMantenimientoTurno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.turnoController = ClientBootstrap.buildTurnoController();
        cargarComboEstados();
        modoAgregar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRegistrar = new javax.swing.JButton();
        TfClient = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JFfecha = new javax.swing.JFormattedTextField();
        JFfecha1 = new javax.swing.JFormattedTextField();
        TfEmpleado = new javax.swing.JTextField();
        BtnActualizar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        CbxEstados = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Turno");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRegistrar.setBackground(new java.awt.Color(51, 102, 255));
        BtnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setText("Agregar");
        BtnRegistrar.setBorder(null);
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 250, 50));

        TfClient.setBackground(new java.awt.Color(255, 255, 255));
        TfClient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfClient.setText("   ID de Cliente");
        TfClient.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        TfClient.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TfClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfClientActionPerformed(evt);
            }
        });
        getContentPane().add(TfClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 250, 40));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("TURN ADD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        JFfecha.setBackground(new java.awt.Color(255, 255, 255));
        JFfecha.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        JFfecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        JFfecha.setText("   Hour");
        JFfecha.setToolTipText("");
        getContentPane().add(JFfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 250, 40));

        JFfecha1.setBackground(new java.awt.Color(255, 255, 255));
        JFfecha1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        JFfecha1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        JFfecha1.setText("   Date");
        JFfecha1.setToolTipText("");
        JFfecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFfecha1ActionPerformed(evt);
            }
        });
        getContentPane().add(JFfecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 250, 40));

        TfEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        TfEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfEmpleado.setText("   ID de Empleado");
        TfEmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        TfEmpleado.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TfEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(TfEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 250, 40));

        BtnActualizar.setBackground(new java.awt.Color(51, 102, 255));
        BtnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        BtnActualizar.setText("Actualizar");
        BtnActualizar.setBorder(null);
        BtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizarMouseClicked(evt);
            }
        });
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 250, 50));

        BtnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        BtnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setBorder(null);
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 250, 50));

        CbxEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CbxEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 250, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Personal data");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText(" Turn data");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/image2_360x680_high_dpi.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        obtenerDatos();
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void TfClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfClientActionPerformed

    private void TfEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEmpleadoActionPerformed

    private void JFfecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFfecha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFfecha1ActionPerformed

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        actualizarTurno();
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        eliminarTurno();
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizarMouseClicked

    }//GEN-LAST:event_BtnActualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDMantenimientoTurno dialog = new JDMantenimientoTurno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JComboBox<String> CbxEstados;
    private javax.swing.JFormattedTextField JFfecha;
    private javax.swing.JFormattedTextField JFfecha1;
    private javax.swing.JTextField TfClient;
    private javax.swing.JTextField TfEmpleado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    private void cargarComboEstados() {
        CbxEstados.removeAllItems();

        for (EstadoTurno estado : EstadoTurno.values()) {
            CbxEstados.addItem(estado.name());
        }
    }

    private void actualizarTurno() {
        try {
            String clienteTexto = TfClient.getText().trim();
            String empleadoTexto = TfEmpleado.getText().trim();
            String fechaTexto = JFfecha1.getText().trim();
            String horaTexto = JFfecha.getText().trim();

            int idCliente = Integer.parseInt(clienteTexto);
            int idEmpleado = Integer.parseInt(empleadoTexto);

            EstadoTurno estado = EstadoTurno.valueOf(
                    CbxEstados.getSelectedItem().toString()
            );

            Result<Void> result = turnoController.updateTurno(
                    idTurno,
                    idCliente,
                    fechaTexto,
                    horaTexto,
                    estado,
                    idEmpleado
            );

            if (result.ok) {
                JOptionPane.showMessageDialog(
                        rootPane,
                        result.message,
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE
                );

                this.dispose();

                if (JIFGestionTurnos.instancia != null) {
                    JIFGestionTurnos.instancia.cargarTurnos();
                }

            } else {
                JOptionPane.showMessageDialog(
                        rootPane,
                        result.message,
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "El ID del cliente y del empleado deben ser números válidos",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void obtenerDatos() {
        try {
            String clienteTexto = TfClient.getText().trim();
            String empleadoTexto = TfEmpleado.getText().trim();
            String fechaTexto = JFfecha1.getText().trim();
            String horaTexto = JFfecha.getText().trim();

            int idCliente = Integer.parseInt(clienteTexto);
            int idEmpleado = Integer.parseInt(empleadoTexto);

            DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("d/M/yy");
            DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm");

            LocalDate fecha = LocalDate.parse(fechaTexto, formatoFecha);
            LocalTime hora = LocalTime.parse(horaTexto, formatoHora);

            Turno t = new Turno();
            t.setFecha(fecha);
            t.setHora(hora);
            t.setEstado(EstadoTurno.RESERVADO);
            t.setIdCliente(idCliente);
            t.setIdEmpleado(idEmpleado);

            Result<Void> result = turnoController.createTurno(t);

            if (result.ok) {
                JOptionPane.showMessageDialog(
                        rootPane,
                        result.message,
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE
                );
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(
                        rootPane,
                        result.message,
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "El id del cliente y del empleado deben ser números",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    public void modoAgregar() {
        idTurno = 0;

        TfClient.setText("");
        TfEmpleado.setText("");
        JFfecha1.setText("");
        JFfecha.setText("");

        CbxEstados.setVisible(false);

        BtnRegistrar.setVisible(true);
        BtnActualizar.setVisible(false);
        BtnEliminar.setVisible(false);

        setTitle("Agregar Turno");
        jLabel4.setText("TURN ADD");
    }

    public void cargarDatosTurno(int idTurno, int idCliente, String fecha, String hora,
            String estado, int idEmpleado) {

        this.idTurno = idTurno;

        TfClient.setText(String.valueOf(idCliente));
        TfEmpleado.setText(String.valueOf(idEmpleado));
        JFfecha1.setText(fecha);
        JFfecha.setText(hora);

        CbxEstados.setVisible(true);
        CbxEstados.setSelectedItem(estado);

        BtnRegistrar.setVisible(false);
        BtnActualizar.setVisible(true);
        BtnEliminar.setVisible(true);

        setTitle("Actualizar Turno");
        jLabel4.setText("TURN UPDATE");
    }

    private void eliminarTurno() {
        if (idTurno <= 0) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Debe seleccionar un turno válido",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
                rootPane,
                "¿Seguro que desea eliminar este turno?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        Result<Void> result = turnoController.deleteTurno(idTurno);

        if (result.ok) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    result.message,
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
            );

            this.dispose();

            if (JIFGestionTurnos.instancia != null) {
                JIFGestionTurnos.instancia.cargarTurnos();
            }

        } else {
            JOptionPane.showMessageDialog(
                    rootPane,
                    result.message,
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
}
