/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import client.sesion.AppSession;
import javax.swing.JOptionPane;
import client.controller.AuthController;


/**
 *
 * @author Fabian
 */
public class JfLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfLogin.class.getName());
    private final AuthController authController;

    /**
     * Creates new form JfRegistro
     */
    public JfLogin() {
        initComponents();
        this.authController = ClientBootstrap.buildAuthController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TfUser = new javax.swing.JTextField();
        BtnLogin = new javax.swing.JButton();
        LbOlvidar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LbRegistrarse1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TfPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TfUser.setBackground(new java.awt.Color(255, 255, 255));
        TfUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfUser.setText("    User");
        TfUser.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        TfUser.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfUserActionPerformed(evt);
            }
        });
        getContentPane().add(TfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 250, 40));

        BtnLogin.setBackground(new java.awt.Color(51, 102, 255));
        BtnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("Login");
        BtnLogin.setBorder(null);
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 250, 50));

        LbOlvidar.setBackground(new java.awt.Color(255, 255, 255));
        LbOlvidar.setForeground(new java.awt.Color(0, 102, 255));
        LbOlvidar.setText("I forgot my password?");
        LbOlvidar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbOlvidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbOlvidarMouseClicked(evt);
            }
        });
        getContentPane().add(LbOlvidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Don't have an account yet?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 160, 30));

        LbRegistrarse1.setBackground(new java.awt.Color(0, 51, 255));
        LbRegistrarse1.setForeground(new java.awt.Color(0, 102, 255));
        LbRegistrarse1.setText("Create User");
        LbRegistrarse1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbRegistrarse1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbRegistrarse1MouseClicked(evt);
            }
        });
        getContentPane().add(LbRegistrarse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, -1, 30));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("SYSTEM ACCESS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        TfPassword.setBackground(new java.awt.Color(255, 255, 255));
        TfPassword.setText("Passwor");
        TfPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        getContentPane().add(TfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 250, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/image_360x680_high_dpi.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para registrar núevo usuarios
     *
     * @param evt
     */
    private void LbRegistrarse1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbRegistrarse1MouseClicked
        //Mostramos el formulario en pantalla
        JfRegistrar registrar = new JfRegistrar(this);//Núevo formulario de registrar y le pasamos este formulario
        registrar.setVisible(true);//visualizamos el formulario de registrar
        this.setVisible(false);//Desvisualizamos el de login
    }//GEN-LAST:event_LbRegistrarse1MouseClicked

    private void LbOlvidarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbOlvidarMouseClicked
        JfOlvidar olvidar = new JfOlvidar(this);
        olvidar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LbOlvidarMouseClicked

    /**
     * Metodo para tomar datos ingresados del formulario y auntetificar al
     * server
     *
     * @param evt
     */
    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        //Datos de formulario
        String email = TfUser.getText();
        char[] passArr = TfPassword.getPassword();
        String pass = new String(passArr);

        // Limpiamos el array por seguridad
        java.util.Arrays.fill(passArr, '\0');

        //Esperamos respuesta de los controladores y el server
        var result = authController.login(email, pass);

        //Validamos si el resultado fue ok y madamos mensaje al usuario
        if (result.ok) {
            JOptionPane.showMessageDialog(
                    this,
                    result.message,
                    "Login Correcto",
                    JOptionPane.INFORMATION_MESSAGE
            );
            //Traesmos el MDI de sesion
            MDIPrincipal principal = AppSession.getMainMDI();
            //Dejamos de mostrar el formulario de login en pantalla
            this.setVisible(false);
            //Mostramos el principal

            //Prueba del el App Session
            System.out.println(AppSession.getName() + "\n" + AppSession.getUser() + "\n" + AppSession.getRol() + "\n");
            principal.show();
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    result.message,
                    "Error de Login",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        limpiar();
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void TfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfUserActionPerformed

    /**
     * Metodo para limpiar los campos
     */
    private void limpiar() {
        TfUser.setText("");
        TfPassword.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JfLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JLabel LbOlvidar;
    private javax.swing.JLabel LbRegistrarse1;
    private javax.swing.JPasswordField TfPassword;
    private javax.swing.JTextField TfUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
