/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import client.controller.LoginController;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class JfLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfLogin.class.getName());
    private final LoginController loginUserControler; //Generamos el login controller

    /**
     * Creates new form JfRegistro
     */
    public JfLogin() {
        initComponents();
        this.loginUserControler = ClientBootstrap.builLoginController();//Lo inicializamos en la clase boostrap
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpFondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TfUser = new javax.swing.JTextField();
        BtnLogin = new javax.swing.JButton();
        LbOlvidar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LbRegistrarse1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TfPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        JpFondo.setBackground(new java.awt.Color(255, 255, 255));
        JpFondo.setPreferredSize(new java.awt.Dimension(800, 500));
        JpFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TfUser.setBackground(new java.awt.Color(255, 255, 255));
        TfUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfUser.setText("    User");
        TfUser.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        TfUser.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfUserActionPerformed(evt);
            }
        });
        jPanel2.add(TfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 250, 40));

        BtnLogin.setBackground(new java.awt.Color(153, 0, 255));
        BtnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("Login");
        BtnLogin.setBorder(null);
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 250, 50));

        LbOlvidar.setBackground(new java.awt.Color(255, 255, 255));
        LbOlvidar.setForeground(new java.awt.Color(0, 102, 255));
        LbOlvidar.setText("I forgot my password?");
        LbOlvidar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbOlvidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbOlvidarMouseClicked(evt);
            }
        });
        jPanel2.add(LbOlvidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Don't have an account yet?");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, 30));

        LbRegistrarse1.setBackground(new java.awt.Color(0, 51, 255));
        LbRegistrarse1.setForeground(new java.awt.Color(0, 102, 255));
        LbRegistrarse1.setText("Create User");
        LbRegistrarse1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbRegistrarse1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbRegistrarse1MouseClicked(evt);
            }
        });
        jPanel2.add(LbRegistrarse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, 30));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("SYSTEM ACCESS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        TfPassword.setBackground(new java.awt.Color(255, 255, 255));
        TfPassword.setText("Passwor");
        TfPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel2.add(TfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 250, 40));

        JpFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 500));
        JpFondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/ImagenFondo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        JpFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 440, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfUserActionPerformed

    /**
     * Metodo para tomar datos ingresados del formulario y auntetificar al
     * server
     *
     * @param evt
     */
    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        //Datos de formulario
        String email = TfUser.getText();
        char[] passArr = TfPassword.getPassword();
        String pass = new String(passArr);

        // Limpiamos el array por seguridad
        java.util.Arrays.fill(passArr, '\0');

        //Esperamos respuesta de los controladores y el server
        var result = loginUserControler.login(email, pass);

        //Validamos si el resultado fue ok y madamos mensaje al usuario
        if (result.ok) {
            JOptionPane.showMessageDialog(
                    this,
                    result.message,
                    "Login Correcto",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

        } else {
            JOptionPane.showMessageDialog(
                    this,
                    result.message,
                    "Error de Login",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_BtnLoginActionPerformed

    /**
     * Metodo para registrar núevo usuarios
     *
     * @param evt
     */
    private void LbRegistrarse1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbRegistrarse1MouseClicked
        //Mostramos el formulario en pantalla
        JfRegistrar registrar = new JfRegistrar(this);//Núevo formulario de registrar y le pasamos este formulario
        registrar.setVisible(true);//visualizamos el formulario de registrar
        this.setVisible(false);//Desvisualizamos el de login
    }//GEN-LAST:event_LbRegistrarse1MouseClicked

    private void LbOlvidarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbOlvidarMouseClicked
        JfOlvidar olvidar = new JfOlvidar(this);
        olvidar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LbOlvidarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JfLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JPanel JpFondo;
    private javax.swing.JLabel LbOlvidar;
    private javax.swing.JLabel LbRegistrarse1;
    private javax.swing.JPasswordField TfPassword;
    private javax.swing.JTextField TfUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
