/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import client.controller.ForgetController;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class JfOlvidar extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfOlvidar.class.getName());
    private JfLogin login;
    private final ForgetController forgetUserController;

    /**
     * Creates new form JfOlvidar
     */
    JfOlvidar(JfLogin aThis) {
        initComponents();
        this.login = aThis;
        this.forgetUserController = ClientBootstrap.builLoginControllerForget();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TfName = new javax.swing.JTextField();
        BtnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TfUser = new javax.swing.JTextField();
        TfPhone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recuperar");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TfName.setBackground(new java.awt.Color(255, 255, 255));
        TfName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfName.setText("   Name");
        TfName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        TfName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNameActionPerformed(evt);
            }
        });
        jPanel2.add(TfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 250, 40));

        BtnLogin.setBackground(new java.awt.Color(153, 0, 255));
        BtnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("Update");
        BtnLogin.setBorder(null);
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 250, 50));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Recover Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        TfUser.setBackground(new java.awt.Color(255, 255, 255));
        TfUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfUser.setText("   User");
        TfUser.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        TfUser.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfUserActionPerformed(evt);
            }
        });
        jPanel2.add(TfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 250, 40));

        TfPhone.setBackground(new java.awt.Color(255, 255, 255));
        TfPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfPhone.setText("   Phone Number");
        TfPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        TfPhone.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TfPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPhoneActionPerformed(evt);
            }
        });
        jPanel2.add(TfPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        login.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void TfPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPhoneActionPerformed

    private void TfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfUserActionPerformed

    /**
     * Metodo para el cada evento click del boton del formulrio
     * @param evt 
     */
    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        //Traer datos
        String name = TfName.getText();
        String phone = TfPhone.getText();
        String user = TfUser.getText();
        
        //Esperar respues
        var result = forgetUserController.update(user, name, phone);
        
        //Validar respuesta
        if (!result.ok) {
            JOptionPane.showMessageDialog(this, result.message, "Actualizar", JOptionPane.ERROR_MESSAGE);
            limpiarCampos();
            return;
        }
        
        //Mostrar respuesta
        JOptionPane.showMessageDialog(this, result.message, "Actualizar", JOptionPane.INFORMATION_MESSAGE);
        limpiarCampos();
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void TfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNameActionPerformed

    /**
     * Metodo para limpiar los campos del formulario
     */
    private void limpiarCampos() {
        TfUser.setText("");
        TfPhone.setText("");
        TfName.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new JfOlvidar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JTextField TfName;
    private javax.swing.JTextField TfPhone;
    private javax.swing.JTextField TfUser;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
