/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import client.controller.RegisterUserController;
import client.gateway.LocalServerGateway;
import client.gateway.ServerGateway;
import javax.swing.JOptionPane;
import server.cotroller.AuthController;



/**
 *
 * @author Fabian
 */
public class JfRegistrar extends javax.swing.JFrame {
    //Atributos de la clase
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfRegistrar.class.getName());
    private JfLogin login;//Login para guardar el formulario de logueo
    private final RegisterUserController registerUserController;//Generamos el controlador de registro de la cava client

    /**
     * Para generar núevo formulario de registro
     */
    public JfRegistrar(JfLogin login) {
        initComponents();//Iniciamos componetes
        //Guardamos el formulario enviado por parametro
        this.login = login;
        this.registerUserController = ClientBootstrap.buildRegisterController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpFondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BtnRegistrar = new javax.swing.JButton();
        TfEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TfConfig = new javax.swing.JPasswordField();
        TfPassword = new javax.swing.JPasswordField();
        TfName = new javax.swing.JTextField();
        TfPhoneNumeber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        JpFondo.setBackground(new java.awt.Color(255, 255, 255));
        JpFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRegistrar.setBackground(new java.awt.Color(153, 0, 255));
        BtnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setText("Register");
        BtnRegistrar.setBorder(null);
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 250, 50));

        TfEmail.setBackground(new java.awt.Color(255, 255, 255));
        TfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfEmail.setText("   Email");
        TfEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        TfEmail.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEmailActionPerformed(evt);
            }
        });
        jPanel2.add(TfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 250, 40));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("USER REGISTRATION");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        TfConfig.setBackground(new java.awt.Color(255, 255, 255));
        TfConfig.setText("jPasswordField1");
        TfConfig.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel2.add(TfConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 250, 40));

        TfPassword.setBackground(new java.awt.Color(255, 255, 255));
        TfPassword.setText("jPasswordField1");
        TfPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel2.add(TfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 250, 40));

        TfName.setBackground(new java.awt.Color(255, 255, 255));
        TfName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfName.setText("Name");
        TfName.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        TfName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNameActionPerformed(evt);
            }
        });
        jPanel2.add(TfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 250, 40));

        TfPhoneNumeber.setBackground(new java.awt.Color(255, 255, 255));
        TfPhoneNumeber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfPhoneNumeber.setText("Phone Number");
        TfPhoneNumeber.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        TfPhoneNumeber.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TfPhoneNumeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPhoneNumeberActionPerformed(evt);
            }
        });
        jPanel2.add(TfPhoneNumeber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 250, 40));

        JpFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 500));
        JpFondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/ImagenFondo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        JpFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 440, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed

        //Traer datos ingresados
        String email = TfEmail.getText();
        String number=TfPhoneNumeber.getText();
        String name=TfName.getText();
        
        //Traemos los datos en un arreglo de chart y como get password para que los datos no sean inmutables
        char[] passArr = TfPassword.getPassword();
        char[] confArr = TfConfig.getPassword();

        //Creamos los string de contraseñas
        String pass = new String(passArr);
        String confirm = new String(confArr);

        //Lipiamos los arrays
        java.util.Arrays.fill(passArr, '\0');
        java.util.Arrays.fill(confArr, '\0');
        
        //Resivimos el resultado del controlador del metodo registrar
        var result = registerUserController.registrar(email, pass, confirm,number,name);
        
        //validamos si el resultado es diferente a ok y mostramos mensaje por pantalla
        if (!result.ok) {
            //Generamos el Joption para indicarle al usario que su operación fue fallida
            JOptionPane.showMessageDialog(this,result.message,"Registro",JOptionPane.ERROR_MESSAGE);
            limpiarCampos();//Limpiamos los campos del formulario
            return;
        }
        
        //Le idicamos al usuario que la operación fue exitosa
        JOptionPane.showMessageDialog(this, "Usuario creado correctamente!", "Registro", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    /**
     * Metodo para limpiar los campos del formulario
     */
    private void limpiarCampos() {
        TfEmail.setText("");
        TfPassword.setText("");
        TfConfig.setText("");
        TfEmail.requestFocusInWindow();
        TfPhoneNumeber.setText("");
        TfName.setText("");
    }
    private void TfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEmailActionPerformed
    
    /**
     * Metodo para visualizar el login cuando se cierra registro
     * @param evt 
     */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        login.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void TfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNameActionPerformed

    private void TfPhoneNumeberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPhoneNumeberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPhoneNumeberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JPanel JpFondo;
    private javax.swing.JPasswordField TfConfig;
    private javax.swing.JTextField TfEmail;
    private javax.swing.JTextField TfName;
    private javax.swing.JPasswordField TfPassword;
    private javax.swing.JTextField TfPhoneNumeber;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
