/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import javax.swing.JOptionPane;
import client.controller.AuthController;
import common.dto.Result;

/**
 *
 * @author Fabian
 */
public class JfRegistrar extends javax.swing.JFrame {

    //Atributos de la clase
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfRegistrar.class.getName());
    private JfLogin login;//Login para guardar el formulario de logueo
    private final AuthController authController;//Generamos el controlador de registro de la cava client

    /**
     * Para generar núevo formulario de registro
     */
    public JfRegistrar(JfLogin login) {
        initComponents();//Iniciamos componetes
        //Guardamos el formulario enviado por parametro
        this.login = login;
        this.authController = ClientBootstrap.buildAuthController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRegistrar = new javax.swing.JButton();
        TfEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TfConfig = new javax.swing.JPasswordField();
        TfPassword = new javax.swing.JPasswordField();
        TfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TfPhoneNumeber = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRegistrar.setBackground(new java.awt.Color(51, 102, 255));
        BtnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setText("Register");
        BtnRegistrar.setBorder(null);
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 250, 50));

        TfEmail.setBackground(new java.awt.Color(255, 255, 255));
        TfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfEmail.setText("  Email");
        TfEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        TfEmail.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        TfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(TfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 250, 40));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("USER REGISTRATION");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        TfConfig.setBackground(new java.awt.Color(255, 255, 255));
        TfConfig.setText("jPasswordField1");
        TfConfig.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        getContentPane().add(TfConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 250, 40));

        TfPassword.setBackground(new java.awt.Color(255, 255, 255));
        TfPassword.setText("jPasswordField1");
        TfPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        getContentPane().add(TfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 250, 40));

        TfName.setBackground(new java.awt.Color(255, 255, 255));
        TfName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfName.setText("  Name");
        TfName.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        TfName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(TfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 250, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Personal data");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText(" Access data");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        TfPhoneNumeber.setBackground(new java.awt.Color(255, 255, 255));
        TfPhoneNumeber.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        try {
            TfPhoneNumeber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(TfPhoneNumeber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 250, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/image2_360x680_high_dpi.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para limpiar los campos del formulario
     */
    private void limpiarCampos() {
        TfEmail.setText("");
        TfPassword.setText("");
        TfConfig.setText("");
        TfEmail.requestFocusInWindow();
        TfPhoneNumeber.setText("");
        TfName.setText("");
    }

    /**
     * Metodo para visualizar el login cuando se cierra registro
     *
     * @param evt
     */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        login.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void TfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEmailActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        //Traer datos ingresados
        String email = TfEmail.getText();
        String number = TfPhoneNumeber.getText();
        String name = TfName.getText();

        //Traemos los datos en un arreglo de chart y como get password para que los datos no sean inmutables
        char[] passArr = TfPassword.getPassword();
        char[] confArr = TfConfig.getPassword();

        //Creamos los string de contraseñas
        String pass = new String(passArr);
        String confirm = new String(confArr);

        //Lipiamos los arrays
        java.util.Arrays.fill(passArr, '\0');
        java.util.Arrays.fill(confArr, '\0');

        //Resivimos el resultado del controlador del metodo registrar
        Result<Void> result = authController.register(email, pass, confirm, number, name);

        //validamos si el resultado es diferente a ok y mostramos mensaje por pantalla
        if (!result.ok) {
            //Generamos el Joption para indicarle al usario que su operación fue fallida
            JOptionPane.showMessageDialog(this, result.message, "Registro", JOptionPane.ERROR_MESSAGE);
            limpiarCampos();//Limpiamos los campos del formulario
            return;
        }

        //Le idicamos al usuario que la operación fue exitosa
        JOptionPane.showMessageDialog(this, "Usuario creado correctamente!", "Registro", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JPasswordField TfConfig;
    private javax.swing.JTextField TfEmail;
    private javax.swing.JTextField TfName;
    private javax.swing.JPasswordField TfPassword;
    private javax.swing.JFormattedTextField TfPhoneNumeber;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
