/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import client.sesion.AppSession;
import common.dto.Result;
import java.util.ArrayList;
import java.util.List;
import common.enums.EstadoCuenta;
import common.enums.EstadoPeticion;
import common.enums.EstadoTurno;
import common.enums.TipoSolicitud;
import javax.swing.table.DefaultTableModel;
import server.model.Peticion;
import client.controller.PeticionController;

/**
 *
 * @author Fabian
 */
public class JIFAtender extends javax.swing.JInternalFrame {

    public static JIFAtender instancia;
    private final PeticionController peticionController;
    private boolean cargandoCombos = false;

    /**
     * Creates new form JIFAtender
     */
    public JIFAtender() {
        initComponents();
        instancia = this;
        this.peticionController = ClientBootstrap.buildPeticionController();
        iniciarReloj();
        cargarComboTipo();
        cargarComboEstado();
        cargarPeticiones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        LBFecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAtender = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        CbxEstado = new javax.swing.JComboBox<>();
        CbxTipo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Fecha:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        LBFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LBFecha.setForeground(new java.awt.Color(102, 102, 102));
        LBFecha.setText("00/00/0000");
        getContentPane().add(LBFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Atender Solicitudes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 780, 10));

        JTAtender.setBackground(new java.awt.Color(255, 255, 255));
        JTAtender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JTAtender.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Tipo de Solicitud", "Descripción", "Fecha", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTAtender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTAtenderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTAtender);
        if (JTAtender.getColumnModel().getColumnCount() > 0) {
            JTAtender.getColumnModel().getColumn(0).setResizable(false);
            JTAtender.getColumnModel().getColumn(1).setResizable(false);
            JTAtender.getColumnModel().getColumn(2).setResizable(false);
            JTAtender.getColumnModel().getColumn(3).setResizable(false);
            JTAtender.getColumnModel().getColumn(4).setResizable(false);
            JTAtender.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 780, 480));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setText("   Buscar");
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 40));

        CbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(CbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 110, 40));

        CbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxTipoActionPerformed(evt);
            }
        });
        getContentPane().add(CbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 140, 40));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 800, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/imagen_809x586_alta.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        aplicarFiltros();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void CbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxTipoActionPerformed
        aplicarFiltros();
    }//GEN-LAST:event_CbxTipoActionPerformed

    private void CbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxEstadoActionPerformed
        aplicarFiltros();
    }//GEN-LAST:event_CbxEstadoActionPerformed

    private void JTAtenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTAtenderMouseClicked
        int fila = JTAtender.getSelectedRow();

        if (fila != -1) {
            int idPeticion = Integer.parseInt(JTAtender.getValueAt(fila, 0).toString());
            String usuario = JTAtender.getValueAt(fila, 1).toString();
            String fecha = JTAtender.getValueAt(fila, 4).toString();
            String estado = JTAtender.getValueAt(fila, 5).toString();

            JDMantenimientoPeticion ventana = new JDMantenimientoPeticion(null, true);

            ventana.cargarDatosPeticion(
                    idPeticion,
                    usuario,
                    fecha,
                    estado
            );

            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);

            cargarPeticiones();
        }
    }//GEN-LAST:event_JTAtenderMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxEstado;
    private javax.swing.JComboBox<String> CbxTipo;
    private javax.swing.JTable JTAtender;
    private javax.swing.JLabel LBFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
     private Runnable relojListener;

    private void iniciarReloj() {
        // Definir cómo actualizar el label
        relojListener = () -> LBFecha.setText(AppSession.getFechaHora());

        // Registrarse al reloj global
        AppSession.addListener(relojListener);

        // Inicializar inmediatamente
        LBFecha.setText(AppSession.getFechaHora());
    }

// Cuando cierres la vista, remover el listener
    @Override
    public void dispose() {
        if (relojListener != null) {
            AppSession.removeListener(relojListener);
        }
        super.dispose();
    }

    private void cargarComboTipo() {
        cargandoCombos = true;
        CbxTipo.removeAllItems();
        CbxTipo.addItem("TODOS");
        for (TipoSolicitud t : TipoSolicitud.values()) {
            CbxTipo.addItem(t.toString());
        }
        cargandoCombos = false;
    }

    private void cargarComboEstado() {
        cargandoCombos = true;
        CbxEstado.removeAllItems();
        CbxEstado.addItem("TODOS");
        for (EstadoPeticion p : EstadoPeticion.values()) {
            CbxEstado.addItem(p.toString());
        }
        cargandoCombos = false;
    }

    private ArrayList<TipoSolicitud> cargarListaSolicitud() {
        return new ArrayList<>(List.of(TipoSolicitud.values()));
    }

    private ArrayList<EstadoPeticion> cargarListaEstado() {
        return new ArrayList<>(List.of(EstadoPeticion.values()));
    }

    public void cargarPeticiones() {
        cargarPeticiones("", null, null);
    }

    public void cargarPeticiones(String textoBuscar, TipoSolicitud tipoFiltro, EstadoPeticion estadoFiltro) {

        Result<ArrayList<Peticion>> result = peticionController.loadPendientes();

        if (result == null || !result.ok) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    result != null ? result.message : "Error al cargar peticiones",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        DefaultTableModel model = (DefaultTableModel) JTAtender.getModel();
        model.setRowCount(0);

        ArrayList<Peticion> lista = result.data;

        if (lista == null || lista.isEmpty()) {
            return;
        }

        String filtro = (textoBuscar == null) ? "" : textoBuscar.trim().toLowerCase();

        for (Peticion p : lista) {

            String id = String.valueOf(p.getIdPeticion());
            String usuario = (p.getUsuario() != null && p.getUsuario().getUsername() != null)
                    ? p.getUsuario().getUsername()
                    : "";

            String tipo = (p.getTipo() != null)
                    ? p.getTipo().toString()
                    : "";

            String descripcion = (p.getDetalle() != null)
                    ? p.getDetalle()
                    : "";

            String fecha = (p.getCreadaEn() != null)
                    ? p.getCreadaEn().toString()
                    : "";

            String estado = (p.getEstado() != null)
                    ? p.getEstado().toString()
                    : "";

            boolean coincideTexto = filtro.isEmpty()
                    || id.toLowerCase().contains(filtro)
                    || usuario.toLowerCase().contains(filtro)
                    || tipo.toLowerCase().contains(filtro)
                    || descripcion.toLowerCase().contains(filtro)
                    || fecha.toLowerCase().contains(filtro)
                    || estado.toLowerCase().contains(filtro);

            boolean coincideTipo = (tipoFiltro == null) || p.getTipo() == tipoFiltro;
            boolean coincideEstado = (estadoFiltro == null) || p.getEstado() == estadoFiltro;

            if (coincideTexto && coincideTipo && coincideEstado) {
                model.addRow(new Object[]{
                    p.getIdPeticion(),
                    usuario,
                    tipo,
                    descripcion,
                    fecha,
                    estado
                });
            }
        }
    }

    private void aplicarFiltros() {
        if (cargandoCombos) {
            return;
        }

        String buscar = jTextField1.getText().trim();
        if (buscar.equalsIgnoreCase("Buscar")) {
            buscar = "";
        }

        TipoSolicitud tipo = null;
        EstadoPeticion estado = null;

        if (CbxTipo.getSelectedItem() != null) {
            String tipoSeleccionado = CbxTipo.getSelectedItem().toString().trim();
            if (!tipoSeleccionado.equalsIgnoreCase("TODOS")) {
                tipo = TipoSolicitud.valueOf(tipoSeleccionado);
            }
        }

        if (CbxEstado.getSelectedItem() != null) {
            String estadoSeleccionado = CbxEstado.getSelectedItem().toString().trim();
            if (!estadoSeleccionado.equalsIgnoreCase("TODOS")) {
                estado = EstadoPeticion.valueOf(estadoSeleccionado);
            }
        }

        cargarPeticiones(buscar, tipo, estado);
    }
}
