/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import client.controller.UserController;

import client.sesion.AppSession;
import common.dto.Result;

/**
 *
 * @author Fabian
 */
public class JIFConfiguracion extends javax.swing.JInternalFrame {

    private final UserController controller;

    /**
     * Creates new form JIFConfiguracion
     */
    public JIFConfiguracion() {
        this.controller = ClientBootstrap.buildUserController();
        initComponents();
        iniciarReloj();
        inicializarTextFiel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        LBFecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxfNombreSistema = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxfNombreUsuario = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxfUserEmail = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTNuevaContraseña = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTConfirmar = new javax.swing.JTextPane();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Fecha:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        LBFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LBFecha.setForeground(new java.awt.Color(102, 102, 102));
        LBFecha.setText("00/00/0000");
        getContentPane().add(LBFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Configuración");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 780, 10));

        TxfNombreSistema.setEditable(false);
        TxfNombreSistema.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane1.setViewportView(TxfNombreSistema);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 210, 40));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 800, 80));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Nombre de Usuario");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        TxfNombreUsuario.setEditable(false);
        TxfNombreUsuario.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane2.setViewportView(TxfNombreUsuario);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 210, 40));

        TxfUserEmail.setEditable(false);
        TxfUserEmail.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane3.setViewportView(TxfUserEmail);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 210, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Email del Usuario");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        JTNuevaContraseña.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane4.setViewportView(JTNuevaContraseña);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 210, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Nueva Contraseña");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        JTConfirmar.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane5.setViewportView(JTConfirmar);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 210, 40));

        jButton4.setBackground(new java.awt.Color(51, 102, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Guardar Cambios");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 140, 48));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Confimar Contraseña");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Nombre del Sistema");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/imagen_809x586_alta.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nueva = JTNuevaContraseña.getText().trim();
        String confirmar = JTConfirmar.getText().trim();

        if (nueva.isEmpty() || confirmar.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Debe completar ambos campos.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (!nueva.equals(confirmar)) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Las contraseñas no coinciden.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Result<Void> result = controller.updatePassword(AppSession.getUser(), AppSession.getName(), nueva, confirmar);

        if (result.ok) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    result.message,
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            JTNuevaContraseña.setText("");
            JTConfirmar.setText("");

        } else {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    result.message,
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }

        limpiarCampos();

    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane JTConfirmar;
    private javax.swing.JTextPane JTNuevaContraseña;
    private javax.swing.JLabel LBFecha;
    private javax.swing.JTextPane TxfNombreSistema;
    private javax.swing.JTextPane TxfNombreUsuario;
    private javax.swing.JTextPane TxfUserEmail;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
    private Runnable relojListener;

    private void iniciarReloj() {
        // Definir cómo actualizar el label
        relojListener = () -> LBFecha.setText(AppSession.getFechaHora());

        // Registrarse al reloj global
        AppSession.addListener(relojListener);

        // Inicializar inmediatamente
        LBFecha.setText(AppSession.getFechaHora());
    }

// Cuando cierres la vista, remover el listener
    @Override
    public void dispose() {
        if (relojListener != null) {
            AppSession.removeListener(relojListener);
        }
        super.dispose();
    }

    private void inicializarTextFiel() {
        TxfNombreSistema.setEditable(false);
        TxfNombreUsuario.setEditable(false);
        TxfUserEmail.setEditable(false);

        TxfNombreSistema.setText("TunoSync");
        TxfNombreUsuario.setText(AppSession.getName());
        TxfUserEmail.setText(AppSession.getUser());
    }

    private void limpiarCampos() {
        JTConfirmar.setText("");
        JTNuevaContraseña.setText("");
    }
}
