/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import client.sesion.AppSession;
import common.dto.Result;
import java.util.List;
import javax.swing.JFrame;
import common.enums.EstadoTurno;
import java.util.ArrayList;
import server.model.Turno;
import client.controller.TurnoController;

/**
 *
 * @author Fabian
 */
public class JIFGestionTurnos extends javax.swing.JInternalFrame {

    public static JIFGestionTurnos instancia;
    private final TurnoController turnoController;
    private boolean cargandoCombo = false;

    /**
     * Creates new form JIFGestionTurnos
     */
    public JIFGestionTurnos() {
        initComponents();
        instancia = this;
        this.turnoController = ClientBootstrap.buildTurnoController();
        iniciarReloj();
        cargarCombo();
        cargarTurnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        LBFecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTturnos = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        CbxEstadoTurno = new javax.swing.JComboBox<>();
        BtnAgregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Fecha:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        LBFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LBFecha.setForeground(new java.awt.Color(102, 102, 102));
        LBFecha.setText("00/00/0000");
        getContentPane().add(LBFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Turnos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 780, 10));

        JTturnos.setBackground(new java.awt.Color(255, 255, 255));
        JTturnos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JTturnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ID Cliente", "Fecha", "Hora", "Estado", "ID Empleado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTturnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTturnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTturnos);
        if (JTturnos.getColumnModel().getColumnCount() > 0) {
            JTturnos.getColumnModel().getColumn(0).setResizable(false);
            JTturnos.getColumnModel().getColumn(1).setResizable(false);
            JTturnos.getColumnModel().getColumn(2).setResizable(false);
            JTturnos.getColumnModel().getColumn(3).setResizable(false);
            JTturnos.getColumnModel().getColumn(4).setResizable(false);
            JTturnos.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 780, 480));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setText("   Buscar");
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 40));

        CbxEstadoTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbxEstadoTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxEstadoTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(CbxEstadoTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 110, 40));

        BtnAgregar.setBackground(new java.awt.Color(51, 102, 255));
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/Agregar User Blanco.png"))); // NOI18N
        BtnAgregar.setText("Add Turno");
        BtnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 120, 40));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 800, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/imagen_809x586_alta.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        JFrame frame = new JFrame();
        JDMantenimientoTurno turno = new JDMantenimientoTurno(frame, true);

        turno.modoAgregar();

        turno.setLocationRelativeTo(null);
        turno.setVisible(true);

        cargarTurnos();
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        aplicarFiltros();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void CbxEstadoTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxEstadoTurnoActionPerformed
        aplicarFiltros();
    }//GEN-LAST:event_CbxEstadoTurnoActionPerformed

    private void JTturnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTturnosMouseClicked
        int fila = JTturnos.getSelectedRow();

        if (fila != -1) {
            int idTurno = Integer.parseInt(JTturnos.getValueAt(fila, 0).toString());
            int idCliente = Integer.parseInt(JTturnos.getValueAt(fila, 1).toString());
            String fecha = JTturnos.getValueAt(fila, 2).toString();
            String hora = JTturnos.getValueAt(fila, 3).toString();
            String estado = JTturnos.getValueAt(fila, 4).toString();
            int idEmpleado = Integer.parseInt(JTturnos.getValueAt(fila, 5).toString());

            JFrame frame = new JFrame();
            JDMantenimientoTurno turno = new JDMantenimientoTurno(frame, true);

            turno.cargarDatosTurno(
                    idTurno,
                    idCliente,
                    fecha,
                    hora,
                    estado,
                    idEmpleado
            );

            turno.setLocationRelativeTo(null);
            turno.setVisible(true);

            cargarTurnos();
        }
    }//GEN-LAST:event_JTturnosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JComboBox<String> CbxEstadoTurno;
    private javax.swing.JTable JTturnos;
    private javax.swing.JLabel LBFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private Runnable relojListener;

    private void iniciarReloj() {
        // Definir cómo actualizar el label
        relojListener = () -> LBFecha.setText(AppSession.getFechaHora());

        // Registrarse al reloj global
        AppSession.addListener(relojListener);

        // Inicializar inmediatamente
        LBFecha.setText(AppSession.getFechaHora());
    }

// Cuando cierres la vista, remover el listener
    @Override
    public void dispose() {
        instancia = null;

        if (relojListener != null) {
            AppSession.removeListener(relojListener);
        }

        super.dispose();
    }

    private void cargarCombo() {
        cargandoCombo = true;
        CbxEstadoTurno.removeAllItems();
        CbxEstadoTurno.addItem("TODOS");
        for (EstadoTurno e : EstadoTurno.values()) {
            CbxEstadoTurno.addItem(e.toString());
        }
        cargandoCombo = false;
    }

    private ArrayList<EstadoTurno> cargarLista() {
        //List.of Devuelve Lista modificable que contiene todos los valores del enum
        return new ArrayList<>(List.of(EstadoTurno.values()));
    }

    public void cargarTurnos() {
        cargarTurnos("", null);
    }

    private void cargarTurnos(String textoBuscar, EstadoTurno estadoTurno) {
        Result<ArrayList<Turno>> result = turnoController.loadTurnos();

        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) JTturnos.getModel();

        model.setRowCount(0);

        if (result == null || !result.ok || result.data == null) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No se pudieron cargar los turnos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        String filtro = (textoBuscar == null) ? "" : textoBuscar.trim().toLowerCase();

        for (Turno turno : result.data) {
            String idTurno = String.valueOf(turno.getIdTurno());
            String idCliente = String.valueOf(turno.getIdCliente());
            String fecha = turno.getFecha() != null ? turno.getFecha().toString().toLowerCase() : "";
            String hora = turno.getHora() != null ? turno.getHora().toString().toLowerCase() : "";
            String estado = turno.getEstado() != null ? turno.getEstado().name().toLowerCase() : "";
            String idEmpleado = String.valueOf(turno.getIdEmpleado());

            boolean coincideTexto = filtro.isEmpty()
                    || idTurno.contains(filtro)
                    || idCliente.contains(filtro)
                    || fecha.contains(filtro)
                    || hora.contains(filtro)
                    || estado.contains(filtro)
                    || idEmpleado.contains(filtro);

            boolean coincideEstado = (estadoTurno == null) || turno.getEstado() == estadoTurno;

            if (coincideTexto && coincideEstado) {
                model.addRow(new Object[]{
                    turno.getIdTurno(),
                    turno.getIdCliente(),
                    turno.getFecha(),
                    turno.getHora(),
                    turno.getEstado() != null ? turno.getEstado().name() : "",
                    turno.getIdEmpleado()
                });
            }
        }
    }

    private void aplicarFiltros() {
        if (cargandoCombo) {
            return;
        }

        String buscar = jTextField1.getText().trim();
        if (buscar.equalsIgnoreCase("Buscar")) {
            buscar = "";
        }

        EstadoTurno estadoTurno = null;

        if (CbxEstadoTurno.getSelectedItem() != null) {
            String estadoSeleccionado = CbxEstadoTurno.getSelectedItem().toString().trim();
            if (!estadoSeleccionado.equalsIgnoreCase("TODOS")) {
                estadoTurno = EstadoTurno.valueOf(estadoSeleccionado);
            }
        }

        cargarTurnos(buscar, estadoTurno);
    }
}
