/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import client.controller.UserController;
import client.sesion.AppSession;
import common.dto.Result;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import common.enums.EstadoCuenta;
import common.enums.Rol;
import javax.swing.table.DefaultTableModel;
import server.model.Usuario;

/**
 *
 * @author Fabian
 */
public class JIFGestionUsers extends javax.swing.JInternalFrame {

    public static JIFGestionUsers instancia;
    private final UserController userController;
    private boolean cargandoCombos = false;
    private int id = 0;

    /**
     * Creates new form JIFGestionUsers
     */
    public JIFGestionUsers() {
        initComponents();
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.getVerticalScrollBar().setPreferredSize(new java.awt.Dimension(18, 0));
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        instancia = this;
        iniciarReloj();
        cargarComboEstado();
        cargarComboRol();
        this.userController = ClientBootstrap.buildUserController();
        cargarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        LBFecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTUsuarios = new javax.swing.JTable();
        JTFBuscar = new javax.swing.JTextField();
        CbxEstado = new javax.swing.JComboBox<>();
        CbxRol = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Fecha:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        LBFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LBFecha.setForeground(new java.awt.Color(102, 102, 102));
        LBFecha.setText("00/00/0000");
        getContentPane().add(LBFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 780, 10));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        JTUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        JTUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Email", "Rol", "Estado", "ID_Empleado", "ID_Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTUsuarios);
        if (JTUsuarios.getColumnModel().getColumnCount() > 0) {
            JTUsuarios.getColumnModel().getColumn(0).setResizable(false);
            JTUsuarios.getColumnModel().getColumn(0).setPreferredWidth(10);
            JTUsuarios.getColumnModel().getColumn(1).setResizable(false);
            JTUsuarios.getColumnModel().getColumn(2).setResizable(false);
            JTUsuarios.getColumnModel().getColumn(2).setPreferredWidth(100);
            JTUsuarios.getColumnModel().getColumn(3).setResizable(false);
            JTUsuarios.getColumnModel().getColumn(3).setPreferredWidth(20);
            JTUsuarios.getColumnModel().getColumn(4).setResizable(false);
            JTUsuarios.getColumnModel().getColumn(4).setPreferredWidth(20);
            JTUsuarios.getColumnModel().getColumn(5).setResizable(false);
            JTUsuarios.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 780, 470));

        JTFBuscar.setBackground(new java.awt.Color(204, 204, 204));
        JTFBuscar.setForeground(new java.awt.Color(255, 255, 255));
        JTFBuscar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JTFBuscar.setText("   Buscar");
        JTFBuscar.setToolTipText("");
        JTFBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(JTFBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 40));

        CbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(CbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 130, 40));

        CbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxRolActionPerformed(evt);
            }
        });
        getContentPane().add(CbxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 120, 40));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/Agregar User Blanco.png"))); // NOI18N
        jButton1.setText("Add User");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 120, 40));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 800, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/imagen_809x586_alta.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDMantenimientoUsuario ventana = new JDMantenimientoUsuario(null, true);

        ventana.modoAgregar();

        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void CbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxEstadoActionPerformed
        aplicarFiltros();
    }//GEN-LAST:event_CbxEstadoActionPerformed

    private void JTFBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFBuscarActionPerformed
        aplicarFiltros();
    }//GEN-LAST:event_JTFBuscarActionPerformed

    private void CbxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxRolActionPerformed
        aplicarFiltros();
    }//GEN-LAST:event_CbxRolActionPerformed

    private void JTUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTUsuariosMouseClicked

        int fila = JTUsuarios.getSelectedRow();

        if (fila != -1) {
            int idUsuario = Integer.parseInt(JTUsuarios.getValueAt(fila, 0).toString());
            String nombre = JTUsuarios.getValueAt(fila, 1).toString();
            String email = JTUsuarios.getValueAt(fila, 2).toString();
            String rol = JTUsuarios.getValueAt(fila, 3).toString();

            JDMantenimientoUsuario ventana = new JDMantenimientoUsuario(null, true);

            ventana.cargarDatosUsuario(idUsuario, nombre, email, rol);

            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
        }
    }//GEN-LAST:event_JTUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxEstado;
    private javax.swing.JComboBox<String> CbxRol;
    private javax.swing.JTextField JTFBuscar;
    private javax.swing.JTable JTUsuarios;
    private javax.swing.JLabel LBFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
private Runnable relojListener;

    private void iniciarReloj() {
        // Definir cómo actualizar el label
        relojListener = () -> LBFecha.setText(AppSession.getFechaHora());

        // Registrarse al reloj global
        AppSession.addListener(relojListener);

        // Inicializar inmediatamente
        LBFecha.setText(AppSession.getFechaHora());
    }

// Cuando cierres la vista, remover el listener
    @Override
    public void dispose() {
        instancia = null;
        if (relojListener != null) {
            AppSession.removeListener(relojListener);
        }
        super.dispose();
    }

    private void cargarComboEstado() {
        cargandoCombos = true;
        CbxEstado.removeAllItems();
        CbxEstado.addItem("TODOS");
        for (EstadoCuenta e : EstadoCuenta.values()) {
            CbxEstado.addItem(e.toString());
        }
        cargandoCombos = false;
    }

    private void cargarComboRol() {
        cargandoCombos = true;
        CbxRol.removeAllItems();
        CbxRol.addItem("TODOS");
        for (Rol r : Rol.values()) {
            CbxRol.addItem(r.toString());
        }
        cargandoCombos = false;
    }

    private ArrayList<EstadoCuenta> cargarListaEstado() {
        return new ArrayList<>(List.of(EstadoCuenta.values()));
    }

    private ArrayList<Rol> cargarListaRol() {
        return new ArrayList<>(List.of(Rol.values()));
    }

    public void cargarUsuarios() {
        cargarUsuarios("", null, null);
    }

    public void cargarUsuarios(String textoBuscar, Rol rol, EstadoCuenta estado) {
        Result<ArrayList<Usuario>> result = userController.loadUsers();

        if (result != null && result.ok && result.data != null) {

            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) JTUsuarios.getModel();

            model.setRowCount(0);

            String filtro = (textoBuscar == null) ? "" : textoBuscar.trim().toLowerCase();

            for (Usuario u : result.data) {

                String idUsuario = String.valueOf(u.getIdUsuario());
                String nombre = u.getName() != null ? u.getName().toLowerCase() : "";
                String email = u.getUsername() != null ? u.getUsername().toLowerCase() : "";
                String idEmpleado = u.getIdEmpleado() == -1 ? "" : String.valueOf(u.getIdEmpleado());
                String idCliente = u.getIdCliente() == -1 ? "" : String.valueOf(u.getIdCliente());

                boolean coincideTexto = filtro.isEmpty()
                        || idUsuario.contains(filtro)
                        || nombre.contains(filtro)
                        || email.contains(filtro)
                        || idEmpleado.contains(filtro)
                        || idCliente.contains(filtro);

                boolean coincideRol = (rol == null) || u.getRol() == rol;
                boolean coincideEstado = (estado == null) || u.getEstado() == estado;

                if (coincideTexto && coincideRol && coincideEstado) {
                    model.addRow(new Object[]{
                        u.getIdUsuario(),
                        u.getName(),
                        u.getUsername(),
                        u.getRol().toString(),
                        u.getEstado().toString(),
                        u.getIdEmpleado() == -1 ? "Sin asignar" : u.getIdEmpleado(),
                        u.getIdCliente() == -1 ? "Sin asignar" : u.getIdCliente()
                    });
                }
            }

        } else {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    result != null ? result.message : "Error al cargar usuarios"
            );
        }
    }

    private void aplicarFiltros() {
        if (cargandoCombos) {
            return;
        }

        String buscar = JTFBuscar.getText().trim();
        if (buscar.equalsIgnoreCase("Buscar")) {
            buscar = "";
        }

        Rol rol = null;
        EstadoCuenta estado = null;

        if (CbxRol.getSelectedItem() != null) {
            String rolSeleccionado = CbxRol.getSelectedItem().toString().trim();

            if (!rolSeleccionado.equalsIgnoreCase("TODOS")) {
                try {
                    rol = Rol.valueOf(rolSeleccionado);
                } catch (IllegalArgumentException e) {
                    rol = null;
                }
            }
        }

        if (CbxEstado.getSelectedItem() != null) {
            String estadoSeleccionado = CbxEstado.getSelectedItem().toString().trim();

            if (!estadoSeleccionado.equalsIgnoreCase("TODOS")) {
                try {
                    estado = EstadoCuenta.valueOf(estadoSeleccionado);
                } catch (IllegalArgumentException e) {
                    estado = null;
                }
            }
        }

        cargarUsuarios(buscar, rol, estado);
        JTFBuscar.setText("Buscar");
    }
}
