/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import client.sesion.AppSession;
import common.dto.Result;
import java.util.ArrayList;
import java.util.List;
import common.enums.EstadoTurno;
import server.model.Turno;
import client.controller.TurnoController;

/**
 *
 * @author Fabian
 */
public class JIFMisTurnos extends javax.swing.JInternalFrame {

    public static JIFMisTurnos instancia;
    private final TurnoController turnoController;
    private boolean cargandoCombo = false;

    /**
     * Creates new form JIFMisTurnos
     */
    public JIFMisTurnos() {
        initComponents();
        instancia = this;
        iniciarReloj();
        cargarComboEstado();
        this.turnoController = ClientBootstrap.buildTurnoController();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        LBFecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTMisTurnos = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        CbxEstado = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Fecha:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        LBFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LBFecha.setForeground(new java.awt.Color(102, 102, 102));
        LBFecha.setText("00/00/0000");
        getContentPane().add(LBFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mis Turnos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 780, 10));

        JTMisTurnos.setBackground(new java.awt.Color(255, 255, 255));
        JTMisTurnos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JTMisTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Fecha", "Hora", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTMisTurnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 780, 470));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setText("   Buscar");
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 40));

        CbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(CbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 130, 40));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 800, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/imagen_809x586_alta.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        aplicarFiltros();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void CbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxEstadoActionPerformed
        aplicarFiltros();
    }//GEN-LAST:event_CbxEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxEstado;
    private javax.swing.JTable JTMisTurnos;
    private javax.swing.JLabel LBFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private Runnable relojListener;

    private void iniciarReloj() {
        // Definir cómo actualizar el label
        relojListener = () -> LBFecha.setText(AppSession.getFechaHora());

        // Registrarse al reloj global
        AppSession.addListener(relojListener);

        // Inicializar inmediatamente
        LBFecha.setText(AppSession.getFechaHora());
    }

// Cuando cierres la vista, remover el listener
    @Override
    public void dispose() {
        if (relojListener != null) {
            AppSession.removeListener(relojListener);
        }
        super.dispose();
    }

    private void cargarComboEstado() {
        cargandoCombo = true;
        CbxEstado.removeAllItems();
        CbxEstado.addItem("TODOS");
        for (EstadoTurno t : EstadoTurno.values()) {
            CbxEstado.addItem(t.toString());
        }
        cargandoCombo = false;
    }

    private ArrayList<EstadoTurno> cargarListaEstado() {
        return new ArrayList<>(List.of(EstadoTurno.values()));
    }

    public void cargarTabla() {
        cargarTabla("", null);
    }

    public void cargarTabla(String textoBuscar, EstadoTurno estadoFiltro) {

        Result<ArrayList<Turno>> result = null;

        if (AppSession.getIdCliete() != -1) {
            result = turnoController.loadTurnosByUser(AppSession.getIdCliete());
        }

        if (AppSession.getIdEmpleado() != -1) {
            result = turnoController.loadTurnosByUser(AppSession.getIdEmpleado());
        }

        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) JTMisTurnos.getModel();

        model.setRowCount(0);

        if (result == null || !result.ok || result.data == null) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No se pudieron cargar los turnos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        String filtro = (textoBuscar == null) ? "" : textoBuscar.trim().toLowerCase();

        ArrayList<Turno> listaTurnos = result.data;

        for (Turno turno : listaTurnos) {
            String id = String.valueOf(turno.getIdTurno());
            String fecha = turno.getFecha() != null ? turno.getFecha().toString().toLowerCase() : "";
            String hora = turno.getHora() != null ? turno.getHora().toString().toLowerCase() : "";
            String estado = turno.getEstado() != null ? turno.getEstado().name().toLowerCase() : "";

            boolean coincideTexto = filtro.isEmpty()
                    || id.contains(filtro)
                    || fecha.contains(filtro)
                    || hora.contains(filtro)
                    || estado.contains(filtro);

            boolean coincideEstado = (estadoFiltro == null) || turno.getEstado() == estadoFiltro;

            if (coincideTexto && coincideEstado) {
                model.addRow(new Object[]{
                    turno.getIdTurno(),
                    turno.getFecha(),
                    turno.getHora(),
                    turno.getEstado() != null ? turno.getEstado().name() : ""
                });
            }
        }
    }

    private void aplicarFiltros() {
        if (cargandoCombo) {
            return;
        }

        String buscar = jTextField1.getText().trim();
        if (buscar.equalsIgnoreCase("Buscar")) {
            buscar = "";
        }

        EstadoTurno estado = null;

        if (CbxEstado.getSelectedItem() != null) {
            String estadoSeleccionado = CbxEstado.getSelectedItem().toString().trim();
            if (!estadoSeleccionado.equalsIgnoreCase("TODOS")) {
                estado = EstadoTurno.valueOf(estadoSeleccionado);
            }
        }

        cargarTabla(buscar, estado);
    }
}
