/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package client.view;

import client.Bootstrap.ClientBootstrap;
import client.sesion.AppSession;
import common.dto.Result;
import common.enums.Rol;
import java.util.ArrayList;
import java.util.List;
import common.enums.TipoSolicitud;
import server.model.Peticion;
import server.model.Usuario;
import client.controller.PeticionController;

/**
 *
 * @author Fabian
 */
public class JIFSolicitud extends javax.swing.JInternalFrame {

    private final PeticionController peticionController;

    /**
     * Creates new form JIFSolicitud
     */
    public JIFSolicitud() {
        initComponents();
        iniciarReloj();
        cargarComboTipos();
        JTUsuario.setText(AppSession.getUser());
        this.peticionController = ClientBootstrap.buildPeticionController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        LBFecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CbxTipoSolicitud = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTUsuario = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Fecha:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        LBFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LBFecha.setForeground(new java.awt.Color(102, 102, 102));
        LBFecha.setText("00/00/0000");
        getContentPane().add(LBFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nueva Solicitud");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 780, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Tipo de Solicitud");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Descripción");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        CbxTipoSolicitud.setBackground(new java.awt.Color(242, 242, 242));
        CbxTipoSolicitud.setForeground(new java.awt.Color(51, 51, 51));
        CbxTipoSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbxTipoSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxTipoSolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(CbxTipoSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 210, 40));

        JTUsuario.setEditable(false);
        JTUsuario.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane1.setViewportView(JTUsuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 630, 40));

        jTextArea1.setBackground(new java.awt.Color(242, 242, 242));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 630, 150));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 630, 10));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        jButton4.setBackground(new java.awt.Color(0, 102, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Enviar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(449, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 800, 80));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Email Usuario");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/imagen_809x586_alta.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbxTipoSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxTipoSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxTipoSolicitudActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String usuario = JTUsuario.getText().trim();
            String detalle = jTextArea1.getText().trim();
            String tipoSeleccionado = CbxTipoSolicitud.getSelectedItem().toString();

            TipoSolicitud tipo = TipoSolicitud.valueOf(tipoSeleccionado);

            Usuario u = new Usuario();
            u.setUsername(usuario);

            Peticion p = new Peticion();
            p.setUsuario(u);
            p.setTipo(tipo);
            p.setDetalle(detalle);

            Result<Void> result = peticionController.sendPeticion(p);

            if (result.ok) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        result.message,
                        "Éxito",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                );

                jTextArea1.setText("");
                CbxTipoSolicitud.setSelectedIndex(0);

            } else {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        result.message,
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxTipoSolicitud;
    private javax.swing.JTextPane JTUsuario;
    private javax.swing.JLabel LBFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    private Runnable relojListener;

    private void iniciarReloj() {
        // Definir cómo actualizar el label
        relojListener = () -> LBFecha.setText(AppSession.getFechaHora());

        // Registrarse al reloj global
        AppSession.addListener(relojListener);

        // Inicializar inmediatamente
        LBFecha.setText(AppSession.getFechaHora());
    }

// Cuando cierres la vista, remover el listener
    @Override
    public void dispose() {
        if (relojListener != null) {
            AppSession.removeListener(relojListener);
        }
        super.dispose();
    }

    private void cargarComboTipos() {
        ArrayList<TipoSolicitud> lista = cargarLista();
        CbxTipoSolicitud.removeAllItems();

        if (AppSession.getRol() != Rol.EMPLEADO) {
            lista.remove(TipoSolicitud.TURNO_COMPLETADO);
            lista.remove(TipoSolicitud.CAMBIO_ROL);
        }

        for (TipoSolicitud t : lista) {
            CbxTipoSolicitud.addItem(t.toString());
        }
    }

    private ArrayList<TipoSolicitud> cargarLista() {
        return new ArrayList<>(List.of(TipoSolicitud.values()));
    }

   
}
