/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package client.view;

import client.sesion.AppSession;
import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JInternalFrame;

/**
 *
 * @author Fabian
 */
public class MDIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MDIPrincipal
     */
    public MDIPrincipal() {
        initComponents();
        JPContenedorBtns.setLayout(new javax.swing.BoxLayout(JPContenedorBtns, javax.swing.BoxLayout.Y_AXIS));
        validarRol();//Metodo para valiar datos
        ajustarContenedorBotones();//Metodo para ajustra botones
        abrirFormulario();

    }

    /**
     * Metodo para cerrar sesion
     */
    private void cerrarAction() {
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        btnCerrarSession = new javax.swing.JButton();
        JPContenedorBtns = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnGestionUsuario = new javax.swing.JButton();
        btnGestionTurno = new javax.swing.JButton();
        btnSolicitud = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();
        btnCofiguracion = new javax.swing.JButton();
        btnMisTurnos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        EMArchivo = new javax.swing.JMenu();
        MDashboard = new javax.swing.JMenuItem();
        MCerrarSession = new javax.swing.JMenuItem();
        EMSistema = new javax.swing.JMenu();
        MSolicitudes = new javax.swing.JMenuItem();
        MHitorial = new javax.swing.JMenuItem();
        JMAteder = new javax.swing.JMenuItem();
        jMGestioUsuarios = new javax.swing.JMenuItem();
        jMGestionTurnos = new javax.swing.JMenuItem();
        EMCuenta = new javax.swing.JMenu();
        MMisturnos = new javax.swing.JMenuItem();
        MConfiguracion = new javax.swing.JMenuItem();
        MCambiarContraseña = new javax.swing.JMenuItem();
        EMAyuda = new javax.swing.JMenu();
        MAcercaDe = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setPreferredSize(new java.awt.Dimension(800, 660));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(0, 102, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("TunoSync");

        btnCerrarSession.setBackground(new java.awt.Color(51, 102, 255));
        btnCerrarSession.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSession.setText("Cerrar Sesión");
        btnCerrarSession.setBorder(null);
        btnCerrarSession.setBorderPainted(false);
        btnCerrarSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSessionActionPerformed(evt);
            }
        });

        JPContenedorBtns.setBackground(new java.awt.Color(249, 249, 249));
        JPContenedorBtns.setForeground(new java.awt.Color(232, 232, 232));
        JPContenedorBtns.setLayout(new javax.swing.BoxLayout(JPContenedorBtns, javax.swing.BoxLayout.LINE_AXIS));

        btnDashboard.setBackground(new java.awt.Color(51, 204, 255));
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/Dashboard.png"))); // NOI18N
        btnDashboard.setText("  Dashboard");
        btnDashboard.setBorder(null);
        btnDashboard.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        JPContenedorBtns.add(btnDashboard);

        btnGestionUsuario.setBackground(new java.awt.Color(51, 204, 255));
        btnGestionUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/Users.png"))); // NOI18N
        btnGestionUsuario.setText("Gestión Usuarios");
        btnGestionUsuario.setBorder(null);
        btnGestionUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionUsuarioMouseClicked(evt);
            }
        });
        JPContenedorBtns.add(btnGestionUsuario);

        btnGestionTurno.setBackground(new java.awt.Color(51, 204, 255));
        btnGestionTurno.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionTurno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/Tiket.png"))); // NOI18N
        btnGestionTurno.setText(" Gestión Turnos");
        btnGestionTurno.setBorder(null);
        btnGestionTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionTurnoMouseClicked(evt);
            }
        });
        btnGestionTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionTurnoActionPerformed(evt);
            }
        });
        JPContenedorBtns.add(btnGestionTurno);

        btnSolicitud.setBackground(new java.awt.Color(51, 204, 255));
        btnSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        btnSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/Formulario.png"))); // NOI18N
        btnSolicitud.setText("Solicitudes Turnos");
        btnSolicitud.setBorder(null);
        btnSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitudMouseClicked(evt);
            }
        });
        JPContenedorBtns.add(btnSolicitud);

        btnHistorial.setBackground(new java.awt.Color(51, 204, 255));
        btnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/historial.png"))); // NOI18N
        btnHistorial.setText("Historial");
        btnHistorial.setBorder(null);
        btnHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialMouseClicked(evt);
            }
        });
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        JPContenedorBtns.add(btnHistorial);

        btnAtender.setBackground(new java.awt.Color(51, 204, 255));
        btnAtender.setForeground(new java.awt.Color(255, 255, 255));
        btnAtender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/ateder.png"))); // NOI18N
        btnAtender.setText("Atender Solicitud");
        btnAtender.setBorder(null);
        btnAtender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtenderMouseClicked(evt);
            }
        });
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });
        JPContenedorBtns.add(btnAtender);

        btnCofiguracion.setBackground(new java.awt.Color(51, 204, 255));
        btnCofiguracion.setForeground(new java.awt.Color(255, 255, 255));
        btnCofiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/configuracion.png"))); // NOI18N
        btnCofiguracion.setText("Configuración");
        btnCofiguracion.setBorder(null);
        btnCofiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCofiguracionMouseClicked(evt);
            }
        });
        btnCofiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCofiguracionActionPerformed(evt);
            }
        });
        JPContenedorBtns.add(btnCofiguracion);

        btnMisTurnos.setBackground(new java.awt.Color(51, 204, 255));
        btnMisTurnos.setForeground(new java.awt.Color(255, 255, 255));
        btnMisTurnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/misTurnos.png"))); // NOI18N
        btnMisTurnos.setText("Mis Turnos");
        btnMisTurnos.setBorder(null);
        btnMisTurnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMisTurnosMouseClicked(evt);
            }
        });
        btnMisTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisTurnosActionPerformed(evt);
            }
        });
        JPContenedorBtns.add(btnMisTurnos);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/images/image3_360x680_high_dpi (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");

        menuBar.setBackground(new java.awt.Color(204, 204, 204));
        menuBar.setBorder(null);

        EMArchivo.setForeground(new java.awt.Color(153, 153, 153));
        EMArchivo.setMnemonic('e');
        EMArchivo.setText("Archivo");

        MDashboard.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MDashboard.setMnemonic('t');
        MDashboard.setText("Inicio");
        MDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDashboardActionPerformed(evt);
            }
        });
        EMArchivo.add(MDashboard);

        MCerrarSession.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MCerrarSession.setMnemonic('y');
        MCerrarSession.setText("Cerrar sesión");
        MCerrarSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCerrarSessionActionPerformed(evt);
            }
        });
        EMArchivo.add(MCerrarSession);

        menuBar.add(EMArchivo);

        EMSistema.setBackground(new java.awt.Color(204, 204, 204));
        EMSistema.setForeground(new java.awt.Color(153, 153, 153));
        EMSistema.setMnemonic('h');
        EMSistema.setText("Sistema");

        MSolicitudes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MSolicitudes.setText("Solicitudes");
        MSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSolicitudesActionPerformed(evt);
            }
        });
        EMSistema.add(MSolicitudes);

        MHitorial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MHitorial.setText("Historial Interno");
        MHitorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MHitorialActionPerformed(evt);
            }
        });
        EMSistema.add(MHitorial);

        JMAteder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMAteder.setText("Atender Solicitud");
        JMAteder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMAtederActionPerformed(evt);
            }
        });
        EMSistema.add(JMAteder);

        jMGestioUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMGestioUsuarios.setText("Gestion Usuarios");
        jMGestioUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestioUsuariosActionPerformed(evt);
            }
        });
        EMSistema.add(jMGestioUsuarios);

        jMGestionTurnos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMGestionTurnos.setText("Gestion Turnos");
        jMGestionTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestionTurnosActionPerformed(evt);
            }
        });
        EMSistema.add(jMGestionTurnos);

        menuBar.add(EMSistema);

        EMCuenta.setForeground(new java.awt.Color(153, 153, 153));
        EMCuenta.setMnemonic('f');
        EMCuenta.setText("Cuenta");

        MMisturnos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MMisturnos.setMnemonic('o');
        MMisturnos.setText("Mis turnos");
        MMisturnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMisturnosActionPerformed(evt);
            }
        });
        EMCuenta.add(MMisturnos);

        MConfiguracion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MConfiguracion.setMnemonic('s');
        MConfiguracion.setText("Configuración");
        MConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MConfiguracionActionPerformed(evt);
            }
        });
        EMCuenta.add(MConfiguracion);

        MCambiarContraseña.setMnemonic('a');
        MCambiarContraseña.setText("Cambiar Contraseña");
        MCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCambiarContraseñaActionPerformed(evt);
            }
        });
        EMCuenta.add(MCambiarContraseña);

        menuBar.add(EMCuenta);

        EMAyuda.setText("Ayuda");

        MAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MAcercaDe.setText("Acerca de");
        EMAyuda.add(MAcercaDe);

        menuBar.add(EMAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnCerrarSession, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(JPContenedorBtns, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(610, 610, 610)
                .addComponent(btnCerrarSession, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(JPContenedorBtns, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        abrirFormulario(AppSession.getBienvenida());
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnCerrarSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSessionActionPerformed
        JfLogin login = new JfLogin();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSessionActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        abrirFormulario(AppSession.getHistorial());
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        abrirFormulario(AppSession.getAtender());
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void btnCofiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCofiguracionActionPerformed
        abrirFormulario(AppSession.getConfiguracion());
    }//GEN-LAST:event_btnCofiguracionActionPerformed

    private void btnGestionTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionTurnoActionPerformed

    private void btnMisTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisTurnosActionPerformed
        abrirFormulario(AppSession.getMisTurnos());
    }//GEN-LAST:event_btnMisTurnosActionPerformed

    private void btnGestionUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionUsuarioMouseClicked
        abrirFormulario(AppSession.getGestionUsers());
    }//GEN-LAST:event_btnGestionUsuarioMouseClicked

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        abrirFormulario(AppSession.getBienvenida());
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnGestionTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionTurnoMouseClicked
        abrirFormulario(AppSession.getGestionTurnos());
    }//GEN-LAST:event_btnGestionTurnoMouseClicked

    private void btnSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitudMouseClicked
        abrirFormulario(AppSession.getSolicitud());
    }//GEN-LAST:event_btnSolicitudMouseClicked

    private void btnHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialMouseClicked
        abrirFormulario(AppSession.getHistorial());
    }//GEN-LAST:event_btnHistorialMouseClicked

    private void btnAtenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtenderMouseClicked
        abrirFormulario(AppSession.getAtender());
    }//GEN-LAST:event_btnAtenderMouseClicked

    private void btnCofiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCofiguracionMouseClicked
        abrirFormulario(AppSession.getConfiguracion());
    }//GEN-LAST:event_btnCofiguracionMouseClicked

    private void btnMisTurnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMisTurnosMouseClicked
        abrirFormulario(AppSession.getMisTurnos());
    }//GEN-LAST:event_btnMisTurnosMouseClicked

    private void MDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDashboardActionPerformed
        abrirFormulario(AppSession.getBienvenida());
    }//GEN-LAST:event_MDashboardActionPerformed

    private void MCerrarSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCerrarSessionActionPerformed
        cerrarAction();
    }//GEN-LAST:event_MCerrarSessionActionPerformed

    private void MSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSolicitudesActionPerformed
        abrirFormulario(AppSession.getSolicitud());
    }//GEN-LAST:event_MSolicitudesActionPerformed

    private void MHitorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MHitorialActionPerformed
        abrirFormulario(AppSession.getHistorial());
    }//GEN-LAST:event_MHitorialActionPerformed

    private void MMisturnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMisturnosActionPerformed
        abrirFormulario(AppSession.getMisTurnos());
    }//GEN-LAST:event_MMisturnosActionPerformed

    private void MConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MConfiguracionActionPerformed
        abrirFormulario(AppSession.getConfiguracion());
    }//GEN-LAST:event_MConfiguracionActionPerformed

    private void MCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCambiarContraseñaActionPerformed
        abrirFormulario(AppSession.getConfiguracion());
    }//GEN-LAST:event_MCambiarContraseñaActionPerformed

    private void JMAtederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMAtederActionPerformed
        abrirFormulario(AppSession.getAtender());
    }//GEN-LAST:event_JMAtederActionPerformed

    private void jMGestioUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestioUsuariosActionPerformed
        abrirFormulario(AppSession.getGestionUsers());
    }//GEN-LAST:event_jMGestioUsuariosActionPerformed

    private void jMGestionTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionTurnosActionPerformed
        abrirFormulario(AppSession.getGestionTurnos());
    }//GEN-LAST:event_jMGestionTurnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EMArchivo;
    private javax.swing.JMenu EMAyuda;
    private javax.swing.JMenu EMCuenta;
    private javax.swing.JMenu EMSistema;
    private javax.swing.JMenuItem JMAteder;
    private javax.swing.JPanel JPContenedorBtns;
    private javax.swing.JMenuItem MAcercaDe;
    private javax.swing.JMenuItem MCambiarContraseña;
    private javax.swing.JMenuItem MCerrarSession;
    private javax.swing.JMenuItem MConfiguracion;
    private javax.swing.JMenuItem MDashboard;
    private javax.swing.JMenuItem MHitorial;
    private javax.swing.JMenuItem MMisturnos;
    private javax.swing.JMenuItem MSolicitudes;
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnCerrarSession;
    private javax.swing.JButton btnCofiguracion;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnGestionTurno;
    private javax.swing.JButton btnGestionUsuario;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnMisTurnos;
    private javax.swing.JButton btnSolicitud;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMGestioUsuarios;
    private javax.swing.JMenuItem jMGestionTurnos;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo para validar un rol Valida rol y asigna cantidad de botones segun
     * el rol de la sesión
     */
    private void validarRol() {
        //Valisamos el rol de la sesión
        switch (AppSession.getRol()) {
            case ADMIN:
                //Quitamos botones
                btnSolicitud.setVisible(false);
                btnMisTurnos.setVisible(false);
                MMisturnos.setVisible(false);
                MSolicitudes.setVisible(false);
                break;
            default:
                btnGestionUsuario.setVisible(false);
                btnGestionTurno.setVisible(false);
                btnHistorial.setVisible(false);
                MHitorial.setVisible(false);
                JMAteder.setVisible(false);
                jMGestioUsuarios.setVisible(false);
                jMGestionTurnos.setVisible(false);
                btnAtender.setVisible(false);
                btnDashboard.setVisible(false);
        }
    }

    /**
     * Metodo para colocar los botones dentro del contenedor de botoes
     */
    private void ajustarContenedorBotones() {
        //Quitamos el valor del contenedor
        JPContenedorBtns.removeAll();
        //Seteamos su layaout
        JPContenedorBtns.setLayout(new javax.swing.BoxLayout(JPContenedorBtns, javax.swing.BoxLayout.Y_AXIS));

        //Generamos Arreglo de botones
        JButton[] botones = {
            btnDashboard,
            btnGestionUsuario,
            btnGestionTurno,
            btnSolicitud,
            btnHistorial,
            btnMisTurnos,
            btnAtender,
            btnCofiguracion
        };

        boolean primero = true;
        int totalBotonesVisibles = 0;

        for (javax.swing.JButton boton : botones) {
            if (boton.isVisible()) {
                if (!primero) {
                    JPContenedorBtns.add(Box.createVerticalStrut(10));
                }

                configurarBoton(boton);
                JPContenedorBtns.add(boton);

                primero = false;
                totalBotonesVisibles++;
            }
        }

        int alto = totalBotonesVisibles * 40 + Math.max(0, totalBotonesVisibles - 1) * 10;

        JPContenedorBtns.setPreferredSize(new Dimension(170, alto));
        JPContenedorBtns.setBounds(100, 70, 170, alto);

        JPContenedorBtns.revalidate();
        JPContenedorBtns.repaint();
    }

    private void configurarBoton(JButton boton) {
        Dimension size = new Dimension(150, 40);
        boton.setPreferredSize(size);
        boton.setMinimumSize(size);
        boton.setMaximumSize(size);
        boton.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
    }

    /**
     * Metodo para abrir formulario interna de la sesión
     *
     * @param jifBienvenida
     */
    private void abrirFormulario(JInternalFrame frame) {

        desktopPane.removeAll();
        desktopPane.repaint();

        frame.setClosable(false);
        frame.setMaximizable(true);
        frame.setIconifiable(false);
        frame.setResizable(true);

        desktopPane.add(frame);
        frame.setVisible(true);

        desktopPane.revalidate();
        desktopPane.repaint();

        try {
            frame.setMaximum(true);
            frame.setSelected(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void abrirFormulario() {

        JInternalFrame frame;

        switch (AppSession.getRol()) {
            case ADMIN:
                frame = AppSession.getBienvenida();
                break;
            case EMPLEADO:
                frame = AppSession.getMisTurnos(); // ajusta esto según tu lógica real
                break;
            case CLIENTE:
                frame = AppSession.getMisTurnos(); // o Bienvenida, según corresponda
                break;
            default:
                frame = AppSession.getBienvenida();
                break;
        }

        abrirFormulario(frame);
    }

}
